version: "3.9"
services:
    ingress:
        image: nginx:1.22
        depends_on:
            - todo-api-service
        volumes:
            - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./frontend:/var/www/static/:ro
        ports:
            - 80:80
        networks:
            - frontend
    todo-api-service:
        build: ./backend
        depends_on:
            - db
        environment:
            - STORAGE=mysql
            - MYSQL_HOST=db
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PWD=${MYSQL_PASSWORD}
            - MYSQL_DB=${MYSQL_DATABASE}
        networks:
            - backend
            - frontend
    db:
        image: mysql:8.0.29-debian
        environment:
            - MYSQL_DATABASE
            - MYSQL_USER
            - MYSQL_PASSWORD
            - MYSQL_ROOT_PASSWORD
        volumes:
            - database:/var/lib/mysql
            - ./init.sql:/docker-entrypoint-initdb.d/1.sql:ro
        networks:
            - backend
volumes:
    database:
networks:
    frontend:
    backend:
